/** Generated by scripts/deploy-guestbook.sh — do not edit by hand after deploy. */
export const L2_CHAIN_ID = 901;
export const L2_RPC_URL = "http://127.0.0.1:9545";

export const GUESTBOOK_ADDRESS = "";

export const GUESTBOOK_ABI = [
  "function sign(string calldata text)",
  "function count() view returns (uint256)",
  "function getMessage(uint256 index) view returns (string)",
  "function getEntry(uint256 index) view returns (tuple(address author, string text, uint64 timestamp))",
  "function getEntries(uint256 offset, uint256 limit) view returns (tuple(address author, string text, uint64 timestamp)[])",
  "function messageCount(address) view returns (uint256)",
  "function MAX_TEXT_BYTES() view returns (uint256)",
  "event MessageSigned(address indexed author, string text, uint256 indexed index, uint64 timestamp)",
];
