/** Generated by scripts/gen-viewer-config.sh — do not edit by hand after deploy. */
export const L1_CHAIN_ID = 900;
export const L2_CHAIN_ID = 901;
export const L1_RPC_URL = "http://127.0.0.1:8545";
export const L2_RPC_URL = "http://127.0.0.1:9545";
export const L2_NODE_RPC_URL = "http://127.0.0.1:9547";

export const BATCHER_ADDRESS = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8";
export const PROPOSER_ADDRESS = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC";
export const BATCH_INBOX_ADDRESS = "0x00289c189bee4e70334629f04cd5ed602b6600eb";
export const DISPUTE_GAME_FACTORY = "0xb3cc73ce8efac81f5c1ee1943b9f1ffeed98c4d2";

export const DISPUTE_GAME_FACTORY_ABI = [
  "function gameCount() view returns (uint256)",
  "function gameAtIndex(uint256 index) view returns (uint32 gameType_, uint64 timestamp_, address proxy_)",
];

export const REFRESH_MS = 5000;
