#!/usr/bin/env bash
# US-008: Deploy Guestbook to L2 and write dapp/config.js
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib.sh"

require_bin forge
require_bin cast
require_bin jq
warn_if_missing_env_file
assert_loopback_url "$L2_RPC_URL" "L2_RPC_URL"
require_eth_address "DEMO_A" "$DEMO_A_ADDRESS"

if [[ -z "${DEMO_A_PRIVATE_KEY:-}" || ! "$DEMO_A_PRIVATE_KEY" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
  echo "ERROR: DEMO_A_PRIVATE_KEY missing or malformed" >&2
  exit 1
fi

wait_for_rpc "$L2_RPC_URL" "L2"

cd "$FORTEL2_ROOT/contracts"
forge build

DEPLOY_JSON=$(forge create src/Guestbook.sol:Guestbook \
  --rpc-url "$L2_RPC_URL" \
  --private-key "$DEMO_A_PRIVATE_KEY" \
  --broadcast \
  --json)

ADDR=$(echo "$DEPLOY_JSON" | jq -r '.deployedTo // .address // empty')

if [[ -z "$ADDR" || "$ADDR" == "null" ]]; then
  echo "ERROR: forge create did not return a deployment address" >&2
  echo "$DEPLOY_JSON" >&2
  exit 1
fi

require_eth_address "Guestbook" "$ADDR"

echo "Guestbook deployed at $ADDR"

L2_RPC_JSON=$(jq -n --arg u "$L2_RPC_URL" '$u')

cat > "$FORTEL2_ROOT/dapp/config.js" << EOF
/** Generated by scripts/deploy-guestbook.sh — do not edit by hand after deploy. */
export const L2_CHAIN_ID = ${L2_CHAIN_ID};
export const L2_RPC_URL = ${L2_RPC_JSON};

export const GUESTBOOK_ADDRESS = "${ADDR}";

export const GUESTBOOK_ABI = [
  "function sign(string calldata text)",
  "function count() view returns (uint256)",
  "function getMessage(uint256 index) view returns (string)",
  "function getEntry(uint256 index) view returns (tuple(address author, string text, uint64 timestamp))",
  "function getEntries(uint256 offset, uint256 limit) view returns (tuple(address author, string text, uint64 timestamp)[])",
  "function messageCount(address) view returns (uint256)",
  "function MAX_TEXT_BYTES() view returns (uint256)",
  "event MessageSigned(address indexed author, string text, uint256 indexed index, uint64 timestamp)",
];
EOF

umask 022
echo "$ADDR" > "$FORTEL2_ROOT/deployments/guestbook.txt"
cast call "$ADDR" "count()(uint256)" --rpc-url "$L2_RPC_URL"
echo "dapp/config.js updated. Serve with: scripts/serve-dapp.sh"
echo "NOTE: redeploy after contract ABI changes; MetaMask may need Reset account after chain reset."
