#!/usr/bin/env bash
# Generate viewer/config.js (+ CSP header file) from env + deploy artifacts.
# Phase 1 (901): loopback L1+L2. Phase 2 Sepolia (852): remote L1 + loopback L2.
# config.js / .csp-header may contain L1 RPC hostnames — gitignored; do not commit.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib.sh"

require_bin jq
warn_if_missing_env_file

if [[ "${L2_CHAIN_ID:-}" == "852" ]]; then
  assert_sepolia_rpc_urls
else
  assert_local_rpc_urls
fi

DEPLOYMENTS="$(deployments_json_path)"
ROLLUP="$DEPLOY_DIR/rollup.json"

if [[ ! -f "$DEPLOYMENTS" ]]; then
  echo "ERROR: missing $DEPLOYMENTS — run deploy scripts first" >&2
  exit 1
fi
if [[ ! -f "$ROLLUP" ]]; then
  echo "ERROR: missing $ROLLUP — run deploy scripts first" >&2
  exit 1
fi

BATCH_INBOX=$(jq -r '.batch_inbox_address // .batch_inbox // empty' "$ROLLUP")
FACTORY=$(jq -r '.DisputeGameFactoryProxy // .disputeGameFactoryProxy // empty' "$DEPLOYMENTS")

require_eth_address "BATCHER_ADDRESS" "${BATCHER_ADDRESS:-}"
require_eth_address "PROPOSER_ADDRESS" "${PROPOSER_ADDRESS:-}"
require_eth_address "BATCH_INBOX_ADDRESS" "$BATCH_INBOX"
require_eth_address "DisputeGameFactoryProxy" "$FACTORY"

L1_RPC_JSON=$(jq -n --arg u "$L1_RPC_URL" '$u')
L2_RPC_JSON=$(jq -n --arg u "$L2_RPC_URL" '$u')
L2_NODE_RPC_JSON=$(jq -n --arg u "$L2_NODE_RPC_URL" '$u')

L1_ORIGIN="$(rpc_origin "$L1_RPC_URL")"
L2_ORIGIN="$(rpc_origin "$L2_RPC_URL")"
L2_NODE_ORIGIN="$(rpc_origin "$L2_NODE_RPC_URL")"

# Always allow common loopback aliases for L2 + Phase 1 Anvil L1.
CONNECT_SRC="'self' http://127.0.0.1:8545 http://localhost:8545"
CONNECT_SRC+=" http://127.0.0.1:9545 http://localhost:9545"
CONNECT_SRC+=" http://127.0.0.1:9547 http://localhost:9547"
# Add live origins (covers Sepolia HTTPS L1 and any non-default ports).
for origin in "$L1_ORIGIN" "$L2_ORIGIN" "$L2_NODE_ORIGIN"; do
  case " $CONNECT_SRC " in
    *" $origin "*) ;;
    *) CONNECT_SRC+=" $origin" ;;
  esac
done

CSP="default-src 'self'; base-uri 'self'; frame-ancestors 'none'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; connect-src ${CONNECT_SRC}; img-src 'self' data:;"

OUT_DIR="$FORTEL2_ROOT/viewer"
OUT="$OUT_DIR/config.js"
CSP_OUT="$OUT_DIR/.csp-header"
mkdir -p "$OUT_DIR"

cat > "$OUT" << EOF
/** Generated by scripts/gen-viewer-config.sh — do not edit by hand after deploy. */
/** May contain private L1 RPC URLs — gitignored; regenerate locally. */
export const L1_CHAIN_ID = ${L1_CHAIN_ID};
export const L2_CHAIN_ID = ${L2_CHAIN_ID};
export const L1_RPC_URL = ${L1_RPC_JSON};
export const L2_RPC_URL = ${L2_RPC_JSON};
export const L2_NODE_RPC_URL = ${L2_NODE_RPC_JSON};

export const BATCHER_ADDRESS = "${BATCHER_ADDRESS}";
export const PROPOSER_ADDRESS = "${PROPOSER_ADDRESS}";
export const BATCH_INBOX_ADDRESS = "${BATCH_INBOX}";
export const DISPUTE_GAME_FACTORY = "${FACTORY}";

export const DISPUTE_GAME_FACTORY_ABI = [
  "function gameCount() view returns (uint256)",
  "function gameAtIndex(uint256 index) view returns (uint32 gameType_, uint64 timestamp_, address proxy_)",
];

export const REFRESH_MS = 5000;
EOF

printf '%s\n' "$CSP" > "$CSP_OUT"

echo "Wrote $OUT"
echo "Wrote $CSP_OUT (served as Content-Security-Policy by serve-viewer.sh)"
echo "  chain L1=$L1_CHAIN_ID L2=$L2_CHAIN_ID"
echo "  L1 RPC (redacted): $(redact_rpc_url "$L1_RPC_URL")"
echo "  batcher=$BATCHER_ADDRESS inbox=$BATCH_INBOX factory=$FACTORY"
