#!/usr/bin/env bash
# Generate blocks/config.js (+ CSP header file) from env.
# Phase 1 (901): loopback L2. Phase 2 Sepolia (852): loopback L2 only.
# config.js / .csp-header may contain RPC hostnames — gitignored; do not commit.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib.sh"

require_bin jq
warn_if_missing_env_file

if [[ "${L2_CHAIN_ID:-}" == "852" ]]; then
  assert_sepolia_rpc_urls
else
  assert_local_rpc_urls
fi

L2_RPC_JSON=$(jq -n --arg u "$L2_RPC_URL" '$u')
L2_ORIGIN="$(rpc_origin "$L2_RPC_URL")"

CONNECT_SRC="'self' http://127.0.0.1:9545 http://localhost:9545"
case " $CONNECT_SRC " in
  *" $L2_ORIGIN "*) ;;
  *) CONNECT_SRC+=" $L2_ORIGIN" ;;
esac

CSP="default-src 'self'; base-uri 'self'; frame-ancestors 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; connect-src ${CONNECT_SRC}; img-src 'self' data:;"

OUT_DIR="$FORTEL2_ROOT/blocks"
OUT="$OUT_DIR/config.js"
CSP_OUT="$OUT_DIR/.csp-header"
mkdir -p "$OUT_DIR"

cat > "$OUT" << EOF
/** Generated by scripts/gen-blocks-config.sh — do not edit by hand after deploy. */
export const L1_CHAIN_ID = ${L1_CHAIN_ID};
export const L2_CHAIN_ID = ${L2_CHAIN_ID};
export const L2_RPC_URL = ${L2_RPC_JSON};
EOF

printf '%s\n' "$CSP" > "$CSP_OUT"

echo "Wrote $OUT"
echo "Wrote $CSP_OUT (served as Content-Security-Policy by serve-blocks.sh)"
echo "  chain L1=$L1_CHAIN_ID L2=$L2_CHAIN_ID"
echo "  L2 RPC (redacted): $(redact_rpc_url "$L2_RPC_URL")"
