#!/usr/bin/env bash
# Generate viewer/config.js from env + deploy artifacts (Phase 1c pipeline viewer).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib.sh"

require_bin jq
warn_if_missing_env_file
assert_local_rpc_urls

DEPLOYMENTS="$FORTEL2_ROOT/deployments/deployments.json"
ROLLUP="$DEPLOY_DIR/rollup.json"

if [[ ! -f "$DEPLOYMENTS" ]]; then
  echo "ERROR: missing $DEPLOYMENTS — run scripts/02-deploy-contracts.sh first" >&2
  exit 1
fi
if [[ ! -f "$ROLLUP" ]]; then
  echo "ERROR: missing $ROLLUP — run scripts/02-deploy-contracts.sh first" >&2
  exit 1
fi

BATCH_INBOX=$(jq -r '.batch_inbox_address // .batch_inbox // empty' "$ROLLUP")
FACTORY=$(jq -r '.DisputeGameFactoryProxy // .disputeGameFactoryProxy // empty' "$DEPLOYMENTS")

require_eth_address "BATCHER_ADDRESS" "${BATCHER_ADDRESS:-}"
require_eth_address "PROPOSER_ADDRESS" "${PROPOSER_ADDRESS:-}"
require_eth_address "BATCH_INBOX_ADDRESS" "$BATCH_INBOX"
require_eth_address "DisputeGameFactoryProxy" "$FACTORY"

L1_RPC_JSON=$(jq -n --arg u "$L1_RPC_URL" '$u')
L2_RPC_JSON=$(jq -n --arg u "$L2_RPC_URL" '$u')
L2_NODE_RPC_JSON=$(jq -n --arg u "$L2_NODE_RPC_URL" '$u')

OUT="$FORTEL2_ROOT/viewer/config.js"
mkdir -p "$FORTEL2_ROOT/viewer"

cat > "$OUT" << EOF
/** Generated by scripts/gen-viewer-config.sh — do not edit by hand after deploy. */
export const L1_CHAIN_ID = ${L1_CHAIN_ID};
export const L2_CHAIN_ID = ${L2_CHAIN_ID};
export const L1_RPC_URL = ${L1_RPC_JSON};
export const L2_RPC_URL = ${L2_RPC_JSON};
export const L2_NODE_RPC_URL = ${L2_NODE_RPC_JSON};

export const BATCHER_ADDRESS = "${BATCHER_ADDRESS}";
export const PROPOSER_ADDRESS = "${PROPOSER_ADDRESS}";
export const BATCH_INBOX_ADDRESS = "${BATCH_INBOX}";
export const DISPUTE_GAME_FACTORY = "${FACTORY}";

export const DISPUTE_GAME_FACTORY_ABI = [
  "function gameCount() view returns (uint256)",
  "function gameAtIndex(uint256 index) view returns (uint32 gameType_, uint64 timestamp_, address proxy_)",
];

export const REFRESH_MS = 5000;
EOF

echo "Wrote $OUT"
echo "  batcher=$BATCHER_ADDRESS inbox=$BATCH_INBOX factory=$FACTORY"
